---
dist: trusty
language: python
sudo: required
cache:
  pip: true
env:
  global:
    - fast_finish: true
    - secure: Tbk9G2NJsx0OzcdU92O4G6NjDYV1rO6oLJ7+ItGbYK93KVLPxh/sTzs8rwncyh3aQFJwF01Z4Liggqddqqko0aiDvlzNOlIyw/cbzszQSGSfdZT5/M6SMmJoy+JhbJLkYGeEX7rK9agVpaVwhz/we73M4cig7NSRCGNZn/7rUialVoLO1wPfHNCzPd0/qTZ/CI8VsxfQGsA7as67RGswZYK/q8DzdngaYh4d8o8OAQsxfqWjruF3XLRkpAdDT3XPmvAes4BOfnZ1HcZqmtqVl4FWIGw0eebSJmTPAGXZ9zRSL+nRlJ+Fb9yqCsBrLHD80eyu7xNnRvZqaMlIF0f3gHEdxCk2BPyKR50+puEz6RKPxeg5zN7vx/zFEyYCyxmJuCfjK54WGV7TnX2oTxTSvTOiNbgZUGxyl97KVUQGj8sOhUVxxj6sMgX6p2T0gTWG1DqonSEweno/65edpLGNXwLNQ5sbjnKF8R42WkDIiDHO/eHOoEzOI9jmvXjw48QbdIYGVonnyEXIIsLbjqNoR6BFHbSQvKq6kDTJZXMgygUyJNKUwY6093Jcvr4UdXYqIxIEuLJJp8i93DPJK6ELc7fvAMD5eK6f8/imQ+URykoYqRkEyfKOgPkFrLacoNqBcSIUt0cODxKTVPcGpY7MhZXOFz0MN9h0WjehDZiNaEE=

matrix:
  include:
    - env: CONFIG=containers/alpine3.4.yml TAGS="3.4"
    - env: CONFIG=containers/alpine3.5.yml TAGS="3.5"
#    - env: CONFIG=containers/alpine3.6.yml TAGS="3.6"
#    - env: CONFIG=containers/alpine3.7.yml TAGS="3.7 latest"
    - env: CONFIG=containers/centos7.yml TAGS="7 latest"
#    - env: CONFIG=containers/centos6.yml TAGS="6"
    - env: CONFIG=containers/debian9.yml TAGS="9 stretch latest"
    - env: CONFIG=containers/debian8.yml TAGS="8 jessie"
    - env: CONFIG=containers/debian7.yml TAGS="7 wheezy"
    - env: CONFIG=containers/fedora27.yml TAGS="27 latest"
    - env: CONFIG=containers/fedora26.yml TAGS="26"
    - env: CONFIG=containers/fedora25.yml TAGS="25"
#    - env: CONFIG=containers/fedora24.yml TAGS="24"
#    - env: CONFIG=containers/ubuntu17.10.yml TAGS="17.10 artful rolling"
#    - env: CONFIG=containers/ubuntu17.04.yml TAGS="17.04 zesty"
    - env: CONFIG=containers/ubuntu16.04.yml TAGS="16.04 xenial latest "
    - env: CONFIG=containers/ubuntu14.04.yml TAGS="14.04 trusty"
    - env: CONFIG=containers/ubuntu12.04.yml TAGS="12.04 precise"
  allow_failures:
    #FIXME: Upstart role not playing nice
    - env: CONFIG=containers/ubuntu14.04.yml TAGS="14.04 trusty"
    - env: CONFIG=containers/ubuntu12.04.yml TAGS="12.04 precise"

services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install --only-upgrade docker-ce -y
install:
  - git clone https://github.com/ansible/ansible-container.git && pip install -e ansible-container[docker]
  - pip install -r pip-requirements.txt
script:
  - molecule check
  - ansible-container --config-file $CONFIG build
deploy:
  - provider: script
    script: bash deploy/deploy.sh
    on:
      branch: master
 notifications:
  email:
    on_failure: change
    on_success: never
