---
dist: trusty
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true
    - secure: Tbk9G2NJsx0OzcdU92O4G6NjDYV1rO6oLJ7+ItGbYK93KVLPxh/sTzs8rwncyh3aQFJwF01Z4Liggqddqqko0aiDvlzNOlIyw/cbzszQSGSfdZT5/M6SMmJoy+JhbJLkYGeEX7rK9agVpaVwhz/we73M4cig7NSRCGNZn/7rUialVoLO1wPfHNCzPd0/qTZ/CI8VsxfQGsA7as67RGswZYK/q8DzdngaYh4d8o8OAQsxfqWjruF3XLRkpAdDT3XPmvAes4BOfnZ1HcZqmtqVl4FWIGw0eebSJmTPAGXZ9zRSL+nRlJ+Fb9yqCsBrLHD80eyu7xNnRvZqaMlIF0f3gHEdxCk2BPyKR50+puEz6RKPxeg5zN7vx/zFEyYCyxmJuCfjK54WGV7TnX2oTxTSvTOiNbgZUGxyl97KVUQGj8sOhUVxxj6sMgX6p2T0gTWG1DqonSEweno/65edpLGNXwLNQ5sbjnKF8R42WkDIiDHO/eHOoEzOI9jmvXjw48QbdIYGVonnyEXIIsLbjqNoR6BFHbSQvKq6kDTJZXMgygUyJNKUwY6093Jcvr4UdXYqIxIEuLJJp8i93DPJK6ELc7fvAMD5eK6f8/imQ+URykoYqRkEyfKOgPkFrLacoNqBcSIUt0cODxKTVPcGpY7MhZXOFz0MN9h0WjehDZiNaEE=
    - env: COMMAND="/usr/bin/systemctl"
matrix:
  include:
    - env: DISTRO=alpine VERSION=3.4 TAGS="3.4"
    - env: DISTRO=alpine VERSION=3.5 TAGS="3.5"
#    - env: DISTRO=alpine VERSION=3.6 TAGS="3.6"
#    - env: DISTRO=alpine VERSION=3.7 TAGS="3.7 latest"
    - env: DISTRO=centos VERSION=7 TAGS="7 latest"
#    - env: DISTRO=centos VERSION=6 TAGS="6"
    - env: DISTRO=debian VERSION=9 TAGS="9 stretch latest"
    - env: DISTRO=debian VERSION=8 TAGS="8 jessie"
    - env: DISTRO=debian VERSION=7 TAGS="7 wheezy"
    - env: DISTRO=fedora VERSION=27 TAGS="27 latest"
    - env: DISTRO=fedora VERSION=26 TAGS="26"
    - env: DISTRO=fedora VERSION=25 TAGS="25"
#    - env: DISTRO=fedora VERSION=24 TAGS="24"
#    - env: DISTRO=ubuntu VERSION=17.10 TAGS="17.10 artful rolling"
#    - env: DISTRO=ubuntu VERSION=17.04 TAGS="17.04 zesty"
    - env: DISTRO=ubuntu VERSION=16.04 TAGS="16.04 xenial latest "
    - env: DISTRO=ubuntu VERSION=14.04 TAGS="14.04 trusty"
    - env: DISTRO=ubuntu VERSION=12.04 TAGS="12.04 precise"

  allow_failures:
    #FIXME: Upstart role not playing nice
    - env: DISTRO=ubuntu VERSION=14.04 TAGS="14.04 trusty"
    - env: DISTRO=ubuntu VERSION=12.04 TAGS="12.04 precise"

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install --only-upgrade docker-ce -y
install:
  - git clone https://github.com/ansible/ansible-container.git && pip install -e ansible-container[docker]
  - pip install -r pip-requirements.txt
script:
  - |
    ansible localhost -m template \
                      -a "src=container.yml.j2 dest=container.yml" \
                      -e "{ "distro": "${DISTRO}", "version": "${VERSION}" }"
  - cat container.yml
  - ansible-container build -- -v

deploy:
  - provider: script
    script: bash deploy/deploy.sh
    on:
      branch: master

notifications:
  email:
    on_failure: change
    on_success: never
