---
lint:
  name: yamllint

provisioner:
  name: ansible
  lint:
    name: ansible-lint

platforms:
  - name: instance

scenario:
  name: default
  create_sequence: []
  check_sequence:
    - lint
  converge_sequence: []
  destroy_sequence: []
  test_sequence:
    - lint
