FROM {{ item.0 }}:{{ item.1 }}

LABEL maintainer="Wilmar den Ouden <info@wilmardenouden.nl>"

ENV container docker

{% if item.0 == centos %}
RUN yum makecache fast \
    && yum update -y \
    && yum install -y \
            python \
            sudo \
            yum-plugin-ovl \
            bash \
    && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
    && yum clean all

{% elif  (item.0 == debian) or (item.0 == ubuntu) %}
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
            systemd \
            systemd-sysv \
            python \
            sudo \
            bash \
            ca-certificates \
    && apt-get clean

{% if item.0 == fedora %}
RUN dnf makecache
    && dnf --assumeyes install \
            python \
            sudo \
            python-devel \
            python2-dnf \
            bash \
    && dnf clean all
{% endif %}

# We only want few core services run in the container.
RUN systemctl mask \
        dev-hugepages.mount \
        sys-fs-fuse-connections.mount \
        sys-kernel-config.mount \
        display-manager.service \
        getty@.service \
        systemd-logind.service \
        systemd-remount-fs.service \
        getty.target \
        graphical.target \
        console-getty.service \
        systemd-vconsole-setup.service \
        kmod-static-nodes.service \
    && systemctl set-default multi-user.target

STOPSIGNAL SIGRTMIN+3

ENTRYPOINT ["/sbin/init"]